name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  project:
    description: 'The name of the GitHub Project'
    required: true
  column:
    description: 'The name of the column to move the issue or pull request to'
    required: true
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: './assign-project.js'
