name: "new-issue"
on:
  issues:
    types: [opened]

jobs:
  build:
    name: New Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install --production
      - run: npm run build
      - uses: ./actions/assign-project
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
