name: "new-issue"
on:
  issues:
    types: [opened]

jobs:
  build:
    name: New Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: yarn install --production
      - run: yarn build
      - uses: ./actions/assign-project
        with:
          project: Test Project
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
